#name: build
#on: [push]
#jobs:
#  ubuntu-test:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Check out repository code 
#        uses: actions/checkout@v2
          
      #- name: create key pair and copy public key from id_rsa.pub
      #  run: |
       #   ssh-keygen
       #   cat ~/.ssh/id_rsa.pub
         
     # The script and documentation in this project are released under the MIT License
     # https://github.com/marketplace/actions/install-ssh-key
     # - name: install SSH key
     #   uses: shimataro/ssh-key-action@v2.1.0
     #   with:
     #    key: ${{secrets.SSH_KEY}}
     #     name: SSH_KEY
     #     known_hosts: ${{secrets.KNOWN_HOSTS}}
     #    config: ${{secrets.}}
     # - name: rsync over ssh
     #   run: rsync ./foo/ user@remote:bar/
      # https://help.github.com/en/articles/workflow-syntax-for-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: Windows Server 2019

on:
- push
- pull_request

jobs:
  ssh:
    name: Connect to github.com
    runs-on: windows-2019
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2.1.0
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: print created files
      run: ls ~/.ssh
    - name: git clone through SSH
      run: git clone git@github.com:shimataro/ssh-key-action.git tmp
  
          
 
