name: build
on: [push]
jobs:
  ubuntu-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code 
        uses: actions/checkout@v2
         
      - name: create key pair and copy public key from id_rsa.pub
        run: |
             ssh-keygen -t rsa
  
          
 
