name: build
on: [push]
jobs:
  ubuntu-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code 
        uses: actions/checkout@v2
      
      - name: Setup SSH keys 
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo ${{ secrets.SSH_KEY_FOR_BUILD_IMAGE }} | base64 --decode --ignore-garbage > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          
      - name: Check properties
        run: | 
          who
          pwd
          
      - name: make new username & password 
        run: |
          sudo adduser 'piriyapong'
          who
          
      - name: generate the keys
        run: |
          ssh-keygen -t dsa -f KEY_FILE
          scp KEY_FILE.pub piriyapong@KEY_FILE
          rm KEY_FILE.pub
   
          
 
